### ISSUE TITLE
Add more motivation

### ISSUE THREAD

**Issue by domenic** [rbuckton/proposal-using-statement#1]
Appealing to precedent in other languages is probably not sufficient for some portion of the audience. It'd be good to give examples, especially ones that build on existing JS patterns or objects.

For example, Streams API readers would be a perfect fit for this: instead of

```js
// Error-prone: should be using try/finally
const reader = stream.getReader();
const { value, done } = await reader.read();
console.log(value, done);
reader.releaseLock();
```

you'd do

```js
using (const reader = stream.getReader()) {
  const { value, done } = await reader.read();
  console.log(value, done);
}
```

**Comment by rbuckton** [comment]
Fixed by f09a1ae4a33b82723086ce190aafc94805fe55ae

**Comment by felixfbecker** [comment]
Aren't streams better consumed with `for await of`?

**Comment by rbuckton** [comment]
@felixfbecker: That only makes sense for a forward-only readable stream (like NodeJS's `Readable`), but not all stream implementations are necessarily forward-only, and `for await of` wouldn't apply to a writable stream (like NodeJS's `Writable`). `for await of` also doesn't account for streams from which you might read only part of the stream, such as reading the headers of an HTTP request before passing the stream onto a different algorithm to parse the response body. `for await of` on streams is a very narrow (albeit fairly common) use case.
