### ISSUE TITLE
TypeScript (?) "API" section is obfuscatory

### ISSUE THREAD

**Issue by domenic** [rbuckton/proposal-using-statement#2]
https://github.com/rbuckton/proposal-using-statement/tree/c0c82628c26be217937e22776f922ba8666a35da#api

I have no idea what this means. I assume it's using TypeScript because I know you work in that language, but I've never heard of `SymbolConstructor` or `readonly`.

It'd be better to describe this using prose.

**Comment by rbuckton** [comment]
I agree that this should also be described using prose, but I also believe that the API code sample is useful.

Fixed by f09a1ae4a33b82723086ce190aafc94805fe55ae
