### ISSUE TITLE
clarify destructuring in head

### ISSUE THREAD

**Issue by bmeck** [rbuckton/proposal-using-statement#5]
```mjs
using (let {x,y} = pt) {
}
```

And if this is intended to call `[Symbol.dispose]` on `pt`, or `y` then `x`. I feel like `y` then `x` has more possibilities of easing usage but doesn't have clearly defined ordering for most users.

**Comment by rbuckton** [comment]
This should already be covered in https://github.com/rbuckton/proposal-using-statement#using-with-binding-patterns. In the example above, `pt` would be disposed, not `x` or `y`. I believe this needs to be consistent with destructuring assignment to avoid a refactoring hazard:

```js
// before
using (let obj = pt) {
  let { x, y } = obj; // `obj` is otherwise unused
  ...
} // `pt` (nee. `obj`) is disposed

// after refactor away single use of `obj`
using (let { x, y } = pt) {
  ...
} // `pt` is disposed.
```

Alternatively:

```js
// before
let x, y;
using ({ x, y } = pt) {
  ...
} // `pt` is disposed

// after refactor `x` and `y` into `using` block
using (let { x, y } = pt) {
  ...
} // `pt` is disposed
```

All of these behaviors are consistent with one another, as well as the existing behavior of a destructuring assignment:

```js
a = { x, y } = b;
a === b;
```

**Comment by rbuckton** [comment]
I've added the above examples to the explainer in 19106dad40dffb8bdc8c905c5f84ac55524f3736.
